method: "lr"
model_name: "llama-70b-3.3"
train_data: "roleplaying__plain"
train_on_policy: true
eval_data:
  - "ai_liar__original_without_answers"
eval_on_policy: true
control_data:
  - "alpaca__plain"
id: "roleplaying_layer_22"
detect_only_start_of_turn: false
val_fraction: 0.2
control_on_policy: true
control_dataset_size: 10000
detect_layers: [22]
reg_coeff: 10
