"""Generate the experiment-config matrix for the data-sanitization (blue-team) study.

Each emitted YAML trains a layer-22 LR probe on one training variant and evaluates it on
the fixed reversed-correlation `test_dist` (plus the auto `_val` split). One file per cell:

  Step 1 (all poisons): training_dist {baseline} + training_dist_{minimal,medium,maximal}
  Step 3 (cats_dogs):   clean_ceiling          -- never-poisoned counterpart
  Step 4 (cats_dogs):   clean_{minimal,medium,maximal} -- collateral-damage cells

Confidence/tense have no deterministic never-poisoned source, so their matched ceiling is
the maximal-guidance cleaned set (training_dist_maximal) -- documented, not a separate cell.

Usage:
    python -m deception_detection.scripts.gen_sanitization_configs
Writes to deception_detection/scripts/configs/sanitization/.
"""

from pathlib import Path

from deception_detection.sanitization import (
    CEILING_VARIANT,
    CLEANED_TRAIN_VARIANTS,
    COLLATERAL_VARIANTS,
    DIAGNOSED_VARIANT,
)

CONFIG_DIR = Path(__file__).parent / "configs" / "sanitization"

# poison cli-name -> dataset base_name
BASE_NAME = {"cats_dogs": "repe_dog_cat", "confidence": "confidence", "tense": "tense"}

# Which training variants to run per poison.
STEP1 = ("training_dist", *CLEANED_TRAIN_VARIANTS)
VARIANTS_BY_POISON = {
    # Steps 1+3+4 plus Idea 1 (diagnosed)
    "cats_dogs": (*STEP1, CEILING_VARIANT, *COLLATERAL_VARIANTS, DIAGNOSED_VARIANT),
    "confidence": (*STEP1, DIAGNOSED_VARIANT),  # Step 1 + Idea 1
    "tense": (*STEP1, DIAGNOSED_VARIANT),       # Step 1 + Idea 1
}

CONFIG_TEMPLATE = """\
# AUTO-GENERATED by gen_sanitization_configs.py -- do not edit by hand.
# Blue-team data-sanitization study: {poison} / {variant}
method: "lr"
model_name: "llama-70b-3.3"
train_data: "{base}__{variant}"
eval_data:
  - "{base}__test_dist"
eval_on_policy: false
control_data:
  - "alpaca__plain"
id: "san_{poison}_{variant}"
detect_only_start_of_turn: false
val_fraction: 0.2
control_on_policy: true
control_dataset_size: 10000
detect_layers: [22]
reg_coeff: 10
"""


def main() -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for poison, variants in VARIANTS_BY_POISON.items():
        base = BASE_NAME[poison]
        for variant in variants:
            content = CONFIG_TEMPLATE.format(poison=poison, variant=variant, base=base)
            path = CONFIG_DIR / f"{poison}__{variant}.yaml"
            path.write_text(content)
            written.append(path)
    print(f"Wrote {len(written)} configs to {CONFIG_DIR}:")
    for p in written:
        print(f"  {p.name}")


if __name__ == "__main__":
    main()
